### GENERAL SETTINGS ###

# Site settings
title: Fungi Québec
description: "Fungi Québec est le travail mycologique de Claude Kaufholtz-Couture."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.fungiquebec.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "_posts/billets"
      type: "posts"
    values:
      layout: "post"
      author: Claude Kaufholtz-Couture
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: flickr
    url: https://www.flickr.com/photos/kaufholtz/


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Author information. Shown on About page.
members:
  - name: Claude Kaufholtz-Couture
    position: Mycologue
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kaufholtz@videotron.ca
      - title: flickr
        url: https://www.flickr.com/photos/kaufholtz/
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Ce site liste le travail mycologique de Claude Kaufholtz-Couture."
email: kaufholtz@videotron.ca
