### GENERAL SETTINGS ###

# Site settings
title: Fungi Québec
description: "Fungi Québec est le travail mycologique de Claude Kaufholtz-Couture."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.fungiquebec.com"
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Ce site liste le travail mycologique de Claude Kaufholtz-Couture."
email: kaufholtz@videotron.ca

# Build settings
markdown: kramdown
permalink: /publications/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
exclude:
  - modele champignon.md

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Claude Kaufholtz-Couture
  -
    scope:
      path: "_champignons"
    values:
      layout: "champignon"
      author: Claude Kaufholtz-Couture

colors:  #in hex code if not noted else
  primary: "#90805E" #"#00b3fe" #"#F70031" 
  primary_rgb: "144,128,94" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#531E12" #"#384452" #"#33004D"
  link: "#90805E"
  link_hover: "#531E12"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: flickr
    url: https://www.flickr.com/photos/kaufholtz/

### GENERAL DATA FOR VARIOUS LOCATIONS ###

collections:
  champignons:
    output: true

# Author information. Shown on About page.
members:
  - name: Claude Kaufholtz-Couture
    position: Mycologue amateur et microscopiste des champignons
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kaufholtzcoutureclaude@gmail.com
      - title: flickr
        url: https://www.flickr.com/photos/kaufholtz/

champs-details:
  - name: autorites
    label: Autorités
  - name: famille
    label: Famille
  - name: genre
    label: Genre
  - name: espece
    label: Espece
  - name: litterature
    label: Littérature
  - name: collection-cueillie
    label: Collection cueillie
  - name: fongarium
    label: Fongarium

champs-description:
  - name: apothecie
    label: Apothécie
  - name: hymenophore
    label: Hyménophore
  - name: face-externe
    label: Face externe
  - name: ascome
    label: Ascome
  - name: capitule
    label: Capitule
  - name: peridium
    label: Péridium
  - name: basidiome
    label: Basidiome
  - name: glebe
    label: Glèbe
  - name: chapeau
    label: Chapeau
  - name: lames
    label: Lames
  - name: pied
    label: Pied
  - name: voile-general
    label: Voile général
  - name: voile-partiel
    label: Voile partiel
  - name: anneau
    label: Anneau
  - name: cortine
    label: Cortine
  - name: chair
    label: Chair
  - name: exhalaison
    label: Exhalaison
  - name: exhalaison-de-la-chair
    label: Exhalaison de la chair
  - name: exhalaison-des-lames
    label: Exhalaison des lames
  - name: saveur
    label: Saveur
  - name: cortex
    label: Cortex
  - name: sporee
    label: Sporée
  - name: asques
    label: Asques
  - name: paraphyses
    label: Paraphyses
  - name: ascospores
    label: Ascospores
  - name: excipulum
    label: Excipulum
  - name: excipulum-medullaire-superieur
    label: Excipulum médullaire supérieur
  - name: excipulum-medullaire-moyen
    label: Excipulum médullaire moyen
  - name: excipulum-medullaire-inferieur
    label: Excipulum médullaire inférieur
  - name: excipulum-ectal
    label: Excipulum ectal
  - name: poils
    label: Poils
  - name: poils-basaux
    label: Poils basaux
  - name: poils-caulinaires
    label: Poils caulinaires
  - name: poils-du-cortex
    label: Poils du cortex
  - name: poils-externes
    label: Poils externes
  - name: poils-lateraux-et-caulinaires
    label: Poils latéraux et caulinaires
  - name: poils-marginaux
    label: Poils marginaux
  - name: poils-mycelien-basaux
    label: Poils mycélien basaux
  - name: poils-peridiaux
    label: Poils péridiaux
  - name: poils-peritheciaux
    label: Poils périthéciaux
  - name: poils-pileiques
    label: Poils piléiques
  - name: basides
    label: Basides
  - name: basidiospores
    label: Basidiospores
  - name: arete-lamellaire
    label: Arête lamellaire
  - name: cellules-marginales-paracystides
    label: Cellules marginales (Paracystides)
  - name: cheilocystides
    label: Cheilocystides
  - name: cheiloleptocystides
    label: Cheiloleptocystides
  - name: cheilomacrocystides
    label: Cheilomacrocystides
  - name: chrysocystides
    label: Chrysocystides
  - name: pleurochrysocystides
    label: Pleurochrysocystides
  - name: pleurocystides
    label: Pleurocystides
  - name: pleuromacrocystides
    label: Pleuromacrocystides
  - name: caulobasides
    label: Caulobasides
  - name: caulocystides
    label: Caulocystides
  - name: caulocystides-medianes
    label: Caulocystides médianes
  - name: caulocystides-sommitales
    label: Caulocystides sommitales
  - name: stipitipellis
    label: Stipitipellis
  - name: stipititrame
    label: Stipititrame
  - name: acanthocytes 
    label: Acanthocytes
  - name: trame-lamellaire
    label: Trame lamellaire
  - name: trame-tubulaire
    label: Trame tubulaire
  - name: pileitrame
    label: Pileitrame
  - name: pileipellis
    label: Pileipellis
  - name: pileocystides
    label: Pileocystides
  - name: boucles
    label: Boucles
  - name: hyphes
    label: Hyphes
  - name: hyphes-de-la-chair
    label: Hyphes de la chair
  - name: hyphes-de-l-anneau
    label: Hyphes de l’anneau
  - name: hyphes-du-pied
    label: Hyphes du pied
  - name: hyphes-glebales
    label: Hyphes glébales
  - name: hyphes-gleopleres
    label: Hyphes gléoplères
  - name: hyphes-hymeniales
    label: Hyphes hyméniales
  - name: hyphes-ligatives
    label: Hyphes ligatives
  - name: hyphes-oleiferes
    label: Hyphes oléifères
  - name: hyphes-pectinees
    label: Hyphes pectinées
  - name: hyphes-primordiales
    label: Hyphes primordiales
  - name: hyphes-setales
    label: Hyphes sétales
  - name: hyphes-squelettiques
    label: Hyphes squelettiques
  - name: hyphes-skeletoligative
    label: Hyphes skeletoligative
  - name: hyphes-subiculaires
    label: Hyphes subiculaires
  - name: hyphes-tramales
    label: Hyphes tramales
  - name: hyphes-vesiculaires
    label: Hyphes vésiculaires
  - name: mode-de-croissance
    label: Mode de croissance
  - name: biotopes
    label: Biotopes
  - name: phenologie
    label: Phénologie
  - name: frequence
    label: Fréquence
  - name: comestibilite
    label: Comestibilité
  - name: reactions-chimiques
    label: Réactions chimiques
  - name: articles
    label: Articles
  - name: publications
    label: Publications
  - name: publications-microscopiques
    label: Publications microscopiques
  - name: synonymie
    label: Synonymie
  - name: nouvelle-espèce
    label: Nouvelle espèce
  - name: remarques
    label: Remarques
  - name: commentaires
    label: Commentaires
  - name: acanthophyses
    label: Acanthophyses
  - name: aiguillons
    label: Aiguillons
  - name: aleurioconidies
    label: Aleurioconidies
  - name: anamorphe
    label: Anamorphe
  - name: anamorphe-conidien
    label: Anamorphe conidien
  - name: arthroconidies
    label: Arthroconidies
  - name: asterohyphidies
    label: Astérohyphidies
  - name: avertissement
    label: Avertissement
  - name: base-du-pied
    label: Base du pied
  - name: base-sterile
    label: Base stérile
  - name: base-stipitiforme
    label: Base stipitiforme
  - name: basidioles
    label: Basidioles
  - name: bibliographies
    label: Bibliographies
  - name: brachybasidioles
    label: Brachybasidioles
  - name: calicule
    label: Calicule
  - name: capillitium
    label: Capillitium
  - name: cellules-hymeniales-diverticulees
    label: Cellules hyméniales diverticulées
  - name: cellules-hymeniales-en-brosses
    label: Cellules hyméniales en brosses
  - name: cellules-peritheciales
    label: Cellules périthéciales
  - name: cellules-stromatiques
    label: Cellules stromatiques
  - name: chancre
    label: Chancre
  - name: chlamydospores
    label: Chlamydospores
  - name: circumcystides
    label: Circumcystides
  - name: clavules
    label: Clavules
  - name: columelle
    label: Columelle
  - name: conidies
    label: Conidies
  - name: conidiome
    label: Conidiome
  - name: conidiophores
    label: Conidiophores
  - name: consistance
    label: Consistance
  - name: contexte
    label: Contexte
  - name: cordons-myceliens
    label: Cordons mycéliens
  - name: cordons-rhizomorphiques
    label: Cordons rhizomorphiques
  - name: cortex-caulinaire
    label: Cortex caulinaire
  - name: cortex-du-pied-et-du-bulbe
    label: Cortex du pied et du bulbe
  - name: cortex-peridial
    label: Cortex péridial
  - name: cortex-sclerotial
    label: Cortex sclérotial
  - name: couches-de-tubes
    label: Couche(s) de tubes
  - name: coupe-sterile
    label: Coupe stérile
  - name: cristaux
    label: Cristaux
  - name: cristaux-d-oxalate
    label: Cristaux d’oxalate
  - name: cuticule
    label: Cuticule
  - name: cutis
    label: Cutis
  - name: cycle
    label: Cycle
  - name: cystides
    label: Cystides
  - name: cystides-hymeniales
    label: Cystides hyméniales
  - name: cystides-intermediaires
    label: Cystides intermédiaires
  - name: cystidioles
    label: Cystidioles
  - name: dendrohyphydies
    label: Dendrohyphydies
  - name: depots-de-pigment-interhyphal
    label: Dépôts de pigment interhyphal
  - name: dermatocystides-caulocystides-et-pileipellis
    label: Dermatocystides (Caulocystides et Pileipellis)
  - name: derniere-correction
    label: Dernière correction
  - name: dicaryophyses
    label: Dicaryophyses
  - name: dichophyses
    label: Dichophyses
  - name: disque-basal
    label: Disque basal
  - name: distribution-et-abondance
    label: Distribution et abondance
  - name: elateres
    label: Élatères
  - name: elements-acanthophyses
    label: Éléments acanthophyses
  - name: elements-cystidioides
    label: Éléments cystidioïdes
  - name: elements-hyphoides
    label: Éléments hyphoïdes
  - name: elements-setoides
    label: Éléments sétoïdes
  - name: elements-steriles
    label: Éléments stériles
  - name: elements-sur-les-cotes
    label: Éléments sur les côtés
  - name: elements-velaires
    label: Éléments vélaires
  - name: endoperidium
    label: Endopéridium
  - name: especes-identification
    label: Espèces Identification
  - name: especes-semblables
    label: Espèces semblables
  - name: exoperidium
    label: Exopéridium
  - name: feutrage-basal
    label: Feutrage basal
  - name: fongarium
    label: Fongarium
  - name: fragments-sporaux
    label: Fragments sporaux
  - name: gleocystides
    label: Gléocystides
  - name: gleocystides-hymeniales
    label: Gléocystides hyméniales
  - name: gleocystides-subhymeniales
    label: Gléocystides subhyméniales
  - name: granules-calcaires
    label: Granules calcaires
  - name: groupe
    label: Groupe
  - name: hymenium
    label: Hyménium
  - name: hymenocystides-cheilocystides-et-pleurocystides
    label: Hyménocystides (Cheilocystides et Pleurocystides)
  - name: hyphidies
    label: Hyphidies
  - name: hyphique
    label: Hyphique
  - name: hypobasides
    label: Hypobasides
  - name: hypoderme
    label: Hypoderme
  - name: hypoge
    label: Hypogé
  - name: hypophylle
    label: Hypophylle
  - name: hypothalle
    label: Hypothalle
  - name: hypothece
    label: Hypothèce
  - name: hysterothece
    label: Hystérothèce
  - name: lamprocystides
    label: Lamprocystides
  - name: lamprocheilocystides
    label: Lamprocheilocystides
  - name: lampropleurocystides
    label: Lampropleurocystides
  - name: lamprocaulocystides
    label: Lamprocaulocystides
  - name: latex
    label: Latex
  - name: leptocystides
    label: Leptocystides
  - name: macrocystides
    label: Macrocystides
  - name: macropleurocystides
    label: Macropleurocystides
  - name: marge
    label: Marge
  - name: marge-et-face-externe
    label: Marge et face externe
  - name: mediostrate
    label: Médiostrate
  - name: medulla
    label: Medulla
  - name: medulla-caulinaire
    label: Medulla caulinaire
  - name: medulla-clavariale
    label: Medulla clavariale
  - name: medulla-clavulaire
    label: Medulla clavulaire
  - name: microconidies
    label: Microconidies
  - name: mycelium-basal
    label: Mycélium basal
  - name: myxocarpe
    label: Myxocarpe
  - name: note-taxonomique
    label: Note taxonomique
  - name: oeuf
    label: Oeuf
  - name: paracapillitium
    label: Paracapillitium
  - name: parasite
    label: Parasite
  - name: paroi-peritheciale
    label: Paroi périthéciale
  - name: peridiole
    label: Péridiole
  - name: peridiopellis
    label: Péridiopellis
  - name: peritheces
    label: Périthèces
  - name: phialoconidies
    label: Phialoconidies
  - name: pieds-steriles
    label: Pieds stériles
  - name: pigments
    label: Pigments
  - name: plasmode
    label: Plasmode
  - name: pores
    label: Pores
  - name: pseudocapillitium
    label: Pseudocapillitium
  - name: pseudocolumelle
    label: Pseudocolumelle
  - name: pseudocystides
    label: Pseudocystides
  - name: pseudo-peridioles
    label: Pseudo péridioles
  - name: receptacle
    label: Réceptacle
  - name: rhizomorphes
    label: Rhizomorphes
  - name: sac-sporifere
    label: Sac sporifère
  - name: sclerocystides
    label: Sclérocystides
  - name: sclerote
    label: Sclérote
  - name: soies
    label: Soies
  - name: soies-hymeniales
    label: Soies hyméniales
  - name: spherocytes
    label: Sphérocytes
  - name: sporocystes
    label: Sporocystes
  - name: stroma
    label: Stroma
  - name: subhymenium
    label: Subhyménium
  - name: subiculum
    label: Subiculum
  - name: substrat
    label: Substrat
  - name: systeme-hyphal
    label: Système hyphal
  - name: textura
    label: Textura
  - name: tomentum-caulinaire
    label: Tomentum caulinaire
  - name: tomentum-pileique
    label: Tomentum piléique
  - name: trame-hymenophorale
    label: Trame hyménophorale
  - name: type
    label: Type
  - name: typique
    label: Typique
  - name: vial
    label: Vial
  - name: voile
    label: Voile
  - name: volve
    label: Volve
  - name: zone-perihymeniale
    label: Zone périhyméniale
