---
nom: Mycena sp.
date: 2016-11-20 00:00:00
image: 
image-originale: 
album-flickr:
  - 
planches:
  - miniature: 
    originale: 

details:
  nom-francais: 
  autorites: 
  ordre: Agaricales
  famille: Mycenaceae
  genre: Mycena
  espece: sp.
  litterature: 
  fongariums:
    - fongarium: cKc0589
      date: 9 octobre 2016
  numero-de-planche-micrographique: 

description:
  acanthocytes: 
  acanthophyses: 
  aiguillons: 
  aleurioconidies: 
  anamorphe: 
  anamorphe-conidien: 
  anneau: 
  apothecie: 
  arete-lamellaire: 
  arthroconidies: 
  articles: 
  ascome: 
  ascospores: 
  asques: 
  asterohyphidies: 
  avertissement: 
  base-du-pied: 
  base-sterile: 
  base-stipitiforme: 
  basides: 
  basidiospores: 
  basidioles: 
  basidiome: 
  bibliographies: 
  biotopes: 
  boucles: 
  brachybasidioles: 
  calicule: 
  capillitium: 
  capitule: 
  caulobasides: 
  caulocystides: 
  caulocystides-medianes: 
  caulocystides-sommitales: 
  cellules-hymeniales-diverticulees: 
  cellules-hymeniales-en-brosses: 
  cellules-marginales-paracystides: 
  cellules-peritheciales: 
  cellules-stromatiques: 
  chair: ferme
  chancre: 
  chapeau: 14 mm Ø, campanulé, brun noirâtre lorsque imbu, hygrophane, brun beige terne
  cheilochrysocystides:
  cheilocystides: 
  cheiloleptocystides: 
  cheilomacrocystides: 
  chlamydospores: 
  chrysocystides: 
  circumcystides: 
  clavules: 
  collection-confirmee-par: 
  collection-determinee-par: Claude Kaufholtz-Couture
  collection-determination-provisoire-par: 
  columelle: 
  commentaires: 
  conidies: 
  conidiome: 
  conidiophores: 
  consistance: 
  contexte: 
  cordons-myceliens: 
  cordons-rhizomorphiques: 
  cortex: 
  cortex-caulinaire: 
  cortex-du-pied-et-du-bulbe: 
  cortex-peridial: 
  cortex-sclerotial: 
  cortine: 
  couches-de-tubes: 
  coupe-sterile: 
  cristaux: 
  cristaux-d-oxalate: 
  cuticule: 
  cutis: 
  cycle: 
  cystides: 
  cystides-hymeniales: 
  cystides-intermediaires: 
  cystidioles: 
  dendrohyphydies: 
  depots-de-pigment-interhyphal: 
  dermatocystides-caulocystides-et-pileipellis: 
  derniere-correction: 
  dicaryophyses: 
  dichophyses: 
  disque-basal: 
  distribution-et-abondance: 
  elateres: 
  elements-acanthophyses: 
  elements-cystidioides: 
  elements-hyphoides: 
  elements-setoides: 
  elements-steriles: 
  elements-sur-les-cotes: 
  elements-velaires: 
  endoperidium: 
  especes-identification: 
  especes-semblables: 
  excipulum: 
  excipulum-medullaire-superieur: 
  excipulum-medullaire-moyen: 
  excipulum-medullaire-inferieur: 
  excipulum-ectal: 
  exhalaison: agréable à fongique
  exhalaison-de-la-chair: 
  exhalaison-des-lames: 
  exoperidium: 
  extremites-hyphales: 
  face-externe: 
  face-poroïde: 
  feutrage-basal: 
  fongarium:
  fragments-sporaux: 
  frequence: 
  glebe: 
  gleocystides: 
  gleocystides-hymeniales: 
  gleocystides-subhymeniales: 
  granules-calcaires: 
  groupe: 
  hymenium: 
  hymenocystides: 
  hymenophore: 
  hyphes: 
  hyphes-de-la-chair: 
  hyphes-de-l-anneau: 
  hyphes-du-pied: 
  hyphes-glebales: 
  hyphes-gleopleres: 
  hyphes-hymeniales: 
  hyphes-ligatives: 
  hyphes-oleiferes: 
  hyphes-pectinees: 
  hyphes-primordiales: 
  hyphes-setales: 
  hyphes-squelettiques: 
  hyphes-skeletoligative: 
  hyphes-subiculaires: 
  hyphes-tramales: 
  hyphes-vesiculaires: 
  hyphidies: 
  hyphique: 
  hypobasides: 
  hypoderme: 
  hypoge: 
  hypophylle: 
  hypothalle: 
  hypothece: 
  hysterothece: 
  lames: décurrentes, espacées, présence de lamelles et de lamellules, beige terne sec
  lamprocystides: 
  lamprocheilocystides: 
  lampropleurocystides: 
  lamprocaulocystides: 
  latex: 
  leptocystides: 
  macrocystides: 
  macropleurocystides: 
  marge: 
  marge-et-face-externe: 
  mediostrate: 
  medulla: 
  medulla-caulinaire: 
  medulla-clavariale: 
  medulla-clavulaire: 
  microconidies: 
  mode-de-croissance: 
  mycelium-basal: 
  myxocarpe: 
  nouvelle-espece: 
  note-taxonomique: 
  oeuf: 
  paracapillitium: 
  paraphyses: 
  parasite: 
  paroi-peritheciale: 
  peridiole: 
  peridiopellis: 
  peridium: 
  peritheces: 
  phenologie: 
  phialoconidies: 
  pied: 28 x 1 mm Ø, cylindrique, pruineux, dont le pied est radicant, crème avec reflet verdâtre, dont la base est plus foncé, reflets jaunâtre, non bulbeux
  pieds-steriles: 
  pigments: 
  pileipellis: 
  pileitrame: 
  pileocystides: 
  plasmode: 
  pleurochrysocystides: 
  pleurocystides: 
  poils: 
  poils-basaux: 
  poils-caulinaires: 
  poils-du-cortex: 
  poils-externes: 
  poils-lateraux-et-caulinaires: 
  poils-marginaux: 
  poils-mycelien-basaux: 
  poils-peridiaux: 
  poils-peritheciaux: 
  poils-pileiques: 
  pores: 
  premiere-mention: 
  pseudocapillitium: 
  pseudocolumelle: 
  pseudocystides: 
  pseudo-peridioles: 
  publications: |
    Smith, Alexander H. North American Species of Mycena, Ann Arbor; University of Michigan Press, London, Geoffrey Cumberlege, Oxford University Press, 1947, 738 p.
  publications-microscopiques: 
  reactions-macrochimiques: 
  receptacle: 
  remarques: 
  repartition: 
  rhizomorphes: 
  sac-sporifere: 
  saveur: raphanoïde, douce
  sclerocystides: 
  sclerote: 
  soies: 
  soies-hymeniales: 
  sporee: blanche
  spores: 
  spherocytes: 
  sporocystes: 
  stipitipellis: 
  stipititrame: 
  stroma: 
  subhymenium: 
  subiculum: 
  substrat: 
  synonymie: 
  systeme-hyphal: 
  textura: 
  tomentum-caulinaire: 
  tomentum-pileique: 
  trame-hymenophorale: 
  trame-lamellaire: 
  trame-tubulaire: 
  type: 
  typique: 
  voile: 
  voile-general: 
  voile-partiel: 
  volve: 
  zone-perihymeniale: 
---
